server:
  port: 8888

spring:
  application:
    name: configserver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/study/msa/native-file-repo
        git:
          uri: https://github.com/FreeCoderKR/msaconfig.git
          default-label: main


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh